
version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    command: npm run dev  -- --host #-d
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    command : air
    volumes:
      - ./backend:/app
volumes:
  db:
    driver: local

