FROM golang

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

COPY ./go.mod ./go.sum ./
RUN go mod download && go mod verify && go mod tidy

COPY . /app
EXPOSE 8080
CMD ["air", "-c", ".air.toml"]
