steps:
  - label: ":docker: Build docker container and deploy"
    command :
      - "if ! docker version; then echo \"Docker not installed, exiting...\"; fi"
      - "if ! docker-compose versio; then echo \"Docker-compose not installed, exiting...\"; fi"
      - "docker-compose up --build -d"
