steps:
  - label: ":docker: Build docker containers"
    command :
      - "if ! docker version; then echo \"Docker not installed, exiting...\"; exit 1; fi"
      - "if ! docker-compose version; then echo \"Docker-compose not installed, exiting...\"; exit 1; fi"
      - "docker-compose build "